---
title: "Horror Movie Visualizations"
subtitle: "STA/ISS 313 - Spring 2023 - Project 1"
author: "Viz Villains- Christopher Tsai, Chris Liang, Jason Zhang, Kevin Ordet"
format: html
editor: visual
---

## Abstract

This project takes data extracted from [The Movie Database](https://www.themoviedb.org) via tmdb API using R `httr`. The purpose of this project is to analyze a) how trends in factors surrounding horror as a genre (e.g. popularity, budgets, etc) have changed over time and b) how different subgenres are associated with popularity of horror films as a whole. This project aims to create compelling visualizations to analyze the two research questions above and deliver findings that can be useful in determining next steps for analysis.

------------------------------------------------------------------------

## Introduction

(1-2 paragraphs): Brief introduction to the dataset. You may repeat some of the information about the dataset provided in the introduction to the dataset on the TidyTuesday repository, paraphrasing on your own terms. Imagine that your project is a standalone document and the grader has no prior knowledge of the dataset.

## Question 1: Title that relates to the question you're answering

### Introduction

In this question we wanted to look at how the popularity of movies changed over the years 1980 to 2022. The first thing we had to do was figure out to measure popularity over time. We decided that measuring how many movies were released in that given year for the theater (which equated to having a budget of over \$2,000,000 in 2022 dollars) would be a good estimator of the popularity of horror movies in a given year. We also decided to look at the popularity of both English and Foreign language horror films to see if there was a difference in the popularity trends of those.

To make this plot we also needed to use the budget and profit data given in the dataset. However, this data was given in the dollar value of the year that the movie was released. In order to scale these amounts to make them comparable, we found a data set that showed how much one dollar in 1950 was worth in that given year. We figured it would make more sense to the audience to have each dollar amount interpreted in terms of 2022 dollars so we reversed the scale to make each dollar amount in budget and profit be in terms of 2022 dollars. We were interested in this question because given the limitations of our data it was one of the only things that might show an interesting trend and we were also interested in how the climate/environment (political, recent big horror movies, etc.) may effect the number of films released in a given year.

### Approach

(1-2 paragraphs): Describe what types of plots you are going to make to address your question. For each plot, provide a clear explanation as to why this plot (e.g. boxplot, barplot, histogram, etc.) is best for providing the information you are asking about. The two plots should be of different types, and at least one of the two plots needs to use either color mapping or facets.

To answer this question we will make 2 line plots using geom_line() and will use geom_smooth() to create a trend line that shows us the short-term trends in the data. We will also be making a scatter plot using geom_point() to look at individual observations of the data.

We first made a scatter plot where each point corresponded to the total number of horror movies made for theatrical release in each year. Because we wanted to look at individual observations (ie. the year 2009 and how many movies were made then)

### Analysis

(2-3 code blocks, 2 figures, text/code comments as needed): In this section, provide the code that generates your plots. Use scale functions to provide nice axis labels and guides. You are welcome to use theme functions to customize the appearance of your plot, but you are not required to do so. All plots must be made with **ggplot2**. Do not use base R or lattice plotting functions.

### Discussion

(1-3 paragraphs): In the Discussion section, interpret the results of your analysis. Identify any trends revealed (or not revealed) by the plots. Speculate about why the data looks the way it does.

## Question 2: Title that relates to the question you're answering

### Introduction

(1-2 paragraphs): Introduction to the question and what parts of the dataset are necessary to answer the question. Also discuss why you're interested in this question.

### Approach

(1-2 paragraphs): Describe what types of plots you are going to make to address your question. For each plot, provide a clear explanation as to why this plot (e.g. boxplot, barplot, histogram, etc.) is best for providing the information you are asking about. The two plots should be of different types, and at least one of the two plots needs to use either color mapping or facets.

### Analysis

(2-3 code blocks, 2 figures, text/code comments as needed): In this section, provide the code that generates your plots. Use scale functions to provide nice axis labels and guides. You are welcome to use theme functions to customize the appearance of your plot, but you are not required to do so. All plots must be made with **ggplot2**. Do not use base R or lattice plotting functions.

### Discussion

(1-3 paragraphs): In the Discussion section, interpret the results of your analysis. Identify any trends revealed (or not revealed) by the plots. Speculate about why the data looks the way it does.
