on: push
name: Check repo organization
jobs:
  check-repo-organization:
    runs-on: self-hosted
    container:
      image: ghcr.io/dukestatsci/r_gh_actions:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Files
      run: |
        checklist::quit_on_failure({
          checklist::check_allowed_files(
          c("_extra/*", "images/*", "_freeze/*",
            "data/*.csv", "data/*.csv", "data/*.xls", "data/*.xlsx", "data/README.md",
            "README.md", "project-01.Rproj",
            "index.qmd", "presentation.qmd", "proposal.qmd", "about.qmd", "_quarto.yml"
            )
          )
        })
      shell: Rscript {0}